more playwright artifact automation

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,4 +1,7 @@
 name: Playwright Tests
+concurrency: 
+  group: ${{ github.ref }}
+  cancel-in-progress: true
 on:
   pull_request:
     branches: [main]
@@ -29,7 +32,7 @@ jobs:
           site_name: "parrit"
 
       - name: Run Playwright tests
-        run: URL=${{steps.netlify.outputs.url}} npx playwright test
+        run: URL=${{steps.netlify.outputs.url}} npx playwright test --reporter=list
 
       - name: Upload Playwright Report
         uses: actions/upload-artifact@v4
@@ -39,14 +42,53 @@ jobs:
           path: playwright-report/
           retention-days: 30
 
-      - name: Deploy to GitHub Pages
+  publish-report:
+    name: Publish HTML Playwright Report
+    if: ${{success() || needs.playwright-tests.result == 'failure'}}
+    needs: playwright-tests
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    env:
+      HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+
+    steps:
+      - name: Checkout GitHub Pages Branch
+        uses: actions/checkout@v4
+        with:
+          ref: gh-pages
+      - name: Set Git User
         run: |
-          BRANCH_NAME=$(echo ${{ github.head_ref }} | sed 's/\//-/g')
-          git config --global user.name 'github-actions[bot]'
-          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          mkdir -p test_runs/$BRANCH_NAME/playwright-report
-          cp -r playwright-report/* test_runs/$BRANCH_NAME/playwright-report/
-          touch test_runs/.nojekyll
-          git add test_runs
-          git commit -m 'Deploy Playwright report to GitHub Pages'
-          git push origin HEAD:gh-pages
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+      - name: Download zipped HTML report
+        uses: actions/download-artifact@v2
+        with:
+          name: playwright-report
+          path: ${{env.HTML_REPORT_URL_PATH}}
+      - name: Push HTML Report
+        timeout-minutes: 3
+        run: |
+          git add .
+          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"
+
+          while true; do
+            git pull --rebase
+            if [ $? -ne 0 ]; then
+              echo "Failed to rebase. Please review manually."
+              exit 1
+            fi
+
+            git push
+            if [ $? -eq 0 ]; then
+              echo "Successfully pushed HTML report to repo."
+              exit 0
+            fi
+          done
+      - name: Output Report URL as Workflow Annotation
+        run: |
+          FULL_HTML_REPORT_URL=https://ysfaran.github.io/playwright-gh-actions-gh-pages/$HTML_REPORT_URL_PATH
+
+          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"
